### ISSUE TITLE
Create Metanorma release dashboard

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/dashboard#4]
This is what @skalee uses in a Gist:

badges.adoc
```adoc
:_shield_style: for-the-badge
:_shield_root: image:https://img.shields.io

{_shield_root}/badge/code-GitHub-000000.svg?style={_shield_style}["GitHub", link="https://github.com/{shield_gh_repo}"]
{_shield_root}/github/languages/top/{shield_gh_repo}.svg?style={_shield_style}["Top Language"]
{_shield_root}/github/issues-raw/{shield_gh_repo}.svg?style={_shield_style}["Issues", link="https://github.com/{shield_gh_repo}/issues"]
{_shield_root}/github/issues-pr-raw/{shield_gh_repo}.svg?style={_shield_style}["PRs", link="https://github.com/{shield_gh_repo}/pulls"] +
{_shield_root}/gem/v/{shield_gem_name}.svg?style={_shield_style}["Gem Version", link="https://rubygems.org/gems/{shield_gem_name}"]
{_shield_root}/gem/dv/{shield_gem_name}/stable.svg?style={_shield_style}["Downloads"]
{_shield_root}/gem/dt/{shield_gem_name}.svg?style={_shield_style}["Downloads"]
{_shield_root}/github/license/{shield_gh_repo}.svg?style={_shield_style}["License"] +
{_shield_root}/github/commit-activity/y/{shield_gh_repo}.svg?style={_shield_style}["Activity"]
{_shield_root}/github/last-commit/{shield_gh_repo}.svg?style={_shield_style}["Activity"]
{_shield_root}/github/contributors/{shield_gh_repo}.svg?style={_shield_style}["Contributors"] +
{_shield_root}/travis/{shield_gh_repo}/master.svg?style={_shield_style}["Build Status", link="https://travis-ci.org/{shield_gh_repo}"]
{_shield_root}/codecov/c/github/{shield_gh_repo}.svg?style={_shield_style}["Test Coverage", link="https://codecov.io/gh/{shield_gh_repo}"]
{_shield_root}/codeclimate/maintainability/{shield_gh_repo}.svg?style={_shield_style}["Code Climate", link="https://codeclimate.com/github/{shield_gh_repo}"] +
{_shield_root}/github/forks/{shield_gh_repo}.svg?label=Fork&style={_shield_style}[]
{_shield_root}/github/stars/{shield_gh_repo}.svg?label=Stars&style={_shield_style}[]
{_shield_root}/github/watchers/{shield_gh_repo}.svg?label=Watch&style={_shield_style}[]
```

dashboard.adoc
```adoc
:source-highlighter: pygments
:pygments-style: native
:pygments-linenums-mode: inline

:toc:

== Ribose

=== OSS Guides

:shield_gh_repo: riboseinc/oss-guides
:shield_gem_name!:

include::_SHIELDS_.adoc[]

Importance: HIGH
Status: EFFECTIVE

* Investigate actual status. (2019 Mar)

=== ActiveUUID

:shield_gh_repo: riboseinc/activeuuid
:shield_gem_name!:

include::_SHIELDS_.adoc[]

Importance: HIGH
Status: READY FOR RELEASE

* Agree on gem name, and make release. (2019 Jan)
* [x] Complete README. (2019 Jan)
* Fix new incompatibilities in Rails 6. (2019 Jan)
* Store UUIDs with rearranged bytes order. (2019 Jan)

=== Attr Masker

:shield_gh_repo: riboseinc/attr_masker
:shield_gem_name: attr_masker

include::_SHIELDS_.adoc[]

Importance: MEDIUM

* Insufficient documentation, whatever it means. (2018)

=== Country to locales mapping

:shield_gh_repo: riboseinc/country_to_locales_mapping
:shield_gem_name: country_to_locales_mapping

include::_SHIELDS_.adoc[]

Importance: LOW

* Create an NPM package

=== EnMail

:shield_gh_repo: riboseinc/enmail
:shield_gem_name: enmail

include::_SHIELDS_.adoc[]

Importance: HIGH
Status: WORKING

* Release soon. (2018 Aug)
* Support Mail 2.7. (2018 Aug)
** [x] Mail 2.7.1, which is supposed to fix the regression, has been released.
** Ensure that there are no more regressions.
* Human-readable names for guides
** Waiting for https://github.com/lsegal/yard/issues/1192.
   (Last checked: 2019 Jan)

=== Flat-File Database

:shield_gh_repo: riboseinc/ffdb„
:shield_gem_name!:

include::_SHIELDS_.adoc[]

Importance: HIGH
Status: STARTED

* Check stdlib for alternative solutions
** [x] *pstore* is not acceptable as it supports stock Ruby marshal only
** [x] *yamlstore* is a pstore which serializes data in a single YAML file
** [x] *gdbm* is not acceptable as it is platform-dependent, and stores data in
   opaque files (both database and database dumps are not enough readable for
   humans)
** [x] *sdbm* is platform-independent (included in Ruby), and stores strings as
   strings, however file layout is fixed and will produce rather ugly diffs
   (though at least readable)
* Basic fetch & store
* Support multiple collections
* Support various marshallers
* Support various database layouts
* Support file locking (flock does not work in NFS)
* Support atomic updates (at least in &ast;NIX file renames are atomic)

...
```

**Comment by opoudjis** [comment]
Too hard, just took badges from READMEs.

https://github.com/metanorma/metanorma-release/blob/master/README.adoc

**Comment by opoudjis** [comment]
Need help with appveyor badges and codeclimate badges. unicode2latex Travis badge and some other badges, for some reason, not displaying even though the build is successful.

**Comment by ronaldtse** [comment]
You sure the Travis badge has org vs com correct?

**Comment by opoudjis** [comment]
`image:https://img.shields.io/travis/metanorma/unicode2latex/master.svg["Travis Build Status", link="https://travis-ci.com/metanorma/unicode2latex"]`

The link is right, and the image source does not differentiate.

**Comment by ronaldtse** [comment]
I think we should probably use the Travis badge directly instead if through shields.io.

**Comment by ronaldtse** [comment]
Done 744b3446f83d300f6ccd479ede605a36a59775b2. Closing.

**Comment by skalee** [comment]
Sorry for reviving this one. Am I correct that these badges are simply copy-pasted from particular READMEs, and manually maintained?

Although GitHub still does not support the AsciiDoctor's `include` directive (github/markup#1095), we can render final HTML in GitHub Actions, then push changes back (https://github.com/ad-m/github-push-action, https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). This should be easy to do, and I can handle that, if you guys believe it is worth doing, which is not necessarily a case.

cc @ronaldtse @opoudjis

**Comment by ronaldtse** [comment]
Yes they are manually maintained, both this dashboard of badges and the badges within the READMEs of each repo. 

I’m not exactly sure of the details you’re proposing - do you mean having this repo automatically fetch the badges from the READMEs of the child repos, or have every child repo’s badges maintained in this repo? Either way it’d be worth doing. 

Feel free to go ahead but the other ticket on Geolexica is more urgent...

**Comment by skalee** [comment]
I meant extracting a partial and re-using it, similarly to what I did in my gist. Or maybe even generating some HTML with ERB or something.

**Comment by ronaldtse** [comment]
It would be best if we can centrally manage the badges. We have been centrally managing our GitHub Actions using the [https://github.com/metanorma/cimas/](Cimas gem) with the CI files located [https://github.com/metanorma/metanorma-build-scripts/tree/master/cimas-config](here).

**Comment by skalee** [comment]
Created #7 so it will not fall off the radar.

**Comment by skalee** [comment]
README refactoring done in #8. Moreover, https://github.com/metanorma/cimas/issues/20 has been created for badges central management feature.
